name: socketServer Deploy
on:
  push:
    branches:
      - main

jobs:
  Auto-Deploy:
    name: socketServer Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH RemoteCommands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          script: |
            cd ~/kutris
            git pull origin main
            pm2 reload index
